[build]
  command = "npm run build"
  publish = "src/assets"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # This ensures your .hbs files are actually uploaded with the code
  included_files = ["src/views/**"]
  # Remove 'hbs' from external_node_modules so esbuild bundles it
  external_node_modules = ["pg"] 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200