[build]
  command = "npm run build"
  publish = "src/assets"
  functions = "netlify/functions" # Point directly to your source folder

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "hbs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200