[build]
  command = "npm run build"
  functions = "functions-dist"  # Changed from netlify/functions
  publish = "src/assets"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200