[build]
  command = "npm run build"
  functions = "functions-dist"
  publish = "src/assets"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "hbs"] # Helps avoid bundling issues with binary modules

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200