[build]
  command = "npm run build"
  publish = "src/assets"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # This tells Netlify to include your views folder inside the function bundle
  included_files = ["src/views/**"] 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200