[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "src/assets"

[functions]
  node_bundler = "esbuild"  # This handles the 'import.meta' error automatically!

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200